# Import external modules
import random
from faker import Faker

from app.server.modules.clock.Clock import Clock

class SecurityAlert:
    """
    Represents a security alert generated by an organization's security systems
    """

    def __init__(self, time: float, alert_type: str, severity: str, description: str):
        self.time = Clock.from_timestamp_to_string(time)
        self.alert_type = alert_type
        self.severity = severity  #high, med, low
        self.description = description

    def stringify(self):
        """
        Returns the security alert as a dictionary in JSON format
        """
        return {
            "timestamp": self.time,
            "alert_type": self.alert_type,
            "severity": self.severity,
            "description": self.description
        }

    @staticmethod
    def get_kql_repr():
        """
        Returns the KQL representation of the SecurityAlert class
        """
        return (
            "SecurityAlert",    # table name
            {                   # type dict
                "timestamp": "datetime",
                "alert_type": "string",
                "severity": "string",
                "description": "string"
            }
        )
